### ISSUE TITLE
error miner_option

### ISSUE THREAD

**Issue by dbosca** [EloWord/abelian#2]
pping miner log rotation due to execution time < 30sec
/var/log/miner/custom/custom.log                                                                                                                                                                                   
Starting Mining instance...                                                                                                                                                                                        
grep: /tmp/miner_option: No such file or directory                                                                                                                                                                 
grep: /tmp/miner_option: No such file  or directory

**Comment by EloWord** [comment]
share with me your Flightsheet here or on my discord, It is just a wrong param format,
